FROM ghcr.io/rjbrown57/binman:latest AS binman
ADD examples/ciExample.yaml /tmp/ciExample.yaml
RUN binman -c /tmp/ciExample.yaml
FROM ubuntu:latest
COPY --from=binman /root/binMan/ /root/binMan/
ENV PATH="$PATH:/root/binMan"
